### ISSUE TITLE
Deixar a barra de pesquisa funcional

### ISSUE THREAD

**Issue by RenanNB3** [FelipeCostaOliveira/Reserva-restaurante#54]
![image](https://github.com/user-attachments/assets/8ad3a215-8c5b-48ba-8438-898a885bd7d8)

**Comment by FelipeCostaOliveira** [comment]
![image](https://github.com/user-attachments/assets/f839504c-1c30-42d4-85c3-7e175cc9cbbb)

Ocultar a mensagem acima que aparece antes de pesquisar algum restaurante @RenanNB3

**Comment by RenanNB3** [comment]
Pronto!
![image](https://github.com/user-attachments/assets/23b30ae4-4097-4caf-9691-0d1f4dc8b914)
