### ISSUE TITLE
Criar tela para o restaurante controlar as reservas

### ISSUE THREAD

**Issue by FelipeCostaOliveira** [FelipeCostaOliveira/Reserva-restaurante#60]
- [x] Estilizar no figma uma tela para o dono do restaurante ter acesso as reservas feitas
- [x] Estilizar no Front end
- [x] Deixar funcional no back end
- [x] Permitir a visualização e controle das reservas feitas e dos horários disponíveis

**Comment by RenanNB3** [comment]
Exibição de reserrvas concluída:
![image](https://github.com/user-attachments/assets/f3285c5e-7de3-44c9-9a7e-6d0cf993747b)

**Comment by RenanNB3** [comment]
Assim que essa issue for aceita, criar outra para implementar a lógica de reservas canceladas.
